---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dingweiqiang.
--- DateTime: 2020-07-07 16:42
---

local plugin_name = "web-basic-defend"

local schema = {
    type = "object",
    properties = {
        switch = {
            type = "string",
            enum = {"on", "off", "warning"},
            default = "on",
        },
        scope = {
            type = "string",
            enum = {"all", "part"},
            default = "all",
        },
        fields = {
            type = "array",
            items = {
                type = "string",
                anyOf = { "args_get", "args_get_names", "args_post","args_post_names",
                          "cookies", "cookies_names", "user_agent", "referer", "uri",
                          "filename", "headers", "headers_names", "body",
                          "upload_filename", "upload_body"
                },
                default = { "args_get", "args_get_names", "args_post","args_post_names",
                            "cookies", "cookies_names", "user_agent", "referer", "uri",
                            "filename", "headers", "headers_names", "body",
                            "upload_filename", "upload_body"
                },
            },
            minItems = 1
        },
        rejected_code = {type = "integer", minimum = 200, maximum = 600,
                         default = 405},
        policy = {
            type = "string",
            enum = {"local", "redis"},
            default = "local",
        },
        redis_host = {
            type = "string", minLength = 2
        },
        redis_port = {
            type = "integer", minimum = 1
        },
        redis_password = {
            type = "string", minLength = 0
        },
        redis_timeout = {
            type = "integer", minimum = 1
        },
    },
    additionalProperties = false,
    required = {"switch"},
}

local _M = {
    version = 0.1,
    priority = 3000,
    name = plugin_name,
    schema = schema,
}

function _M.access(conf, ctx)

end
